Auto Update
shadps4-emu/shadPS4 pull request #1006
Opened 2024-09-21 01:27 UTC by DanielSvoboda

# Update the emulator directly from the application.

In the settings menu, you can enable the "Check for Updates at Startup" option and choose the download channel:

- Stable: stable versions released approximately once a month (These versions are more reliable and tested)
- Unstable: pre-releases with updates almost daily (These may contain bugs and are less stable)

Pending: Depends on [PR-953](https://github.com/shadps4-emu/shadPS4/pull/953) to generate the pre-releases.
After that, the download link will be updated; currently, it is downloading from my fork as a test.
*not tested on macOS

# Images:

![image](https://github.com/user-attachments/assets/1a17b511-4977-4916-ac18-992a321797ce)

You can see the changelog by clicking the button. It is not available if you are using an unstable version and try to update to stable, as there will be no changelog for older versions.
![image](https://github.com/user-attachments/assets/e63dc35a-f68c-4868-ada6-f79210eca525)

The 'About' tab is now called 'Help' and you can also check for updates using this button.
![image](https://github.com/user-attachments/assets/243dd6f7-1ca4-4abf-8308-fcab0a28190e)

Yiga also contributed the icon for the download and dump:
![image](https://github.com/user-attachments/assets/c9ef77df-793c-4c44-82d3-1a8a5d78365b)

Settings:
![image](https://github.com/user-attachments/assets/700c9a70-f275-4851-abe6-6f0cc348f92f)

2024-09-21 09:33 UTC, rambass658 commented
Dont work. Update to previous ver.

2024-09-21 20:45 UTC, polybiusproxy requested changes

2024-09-21 20:45 UTC, polybiusproxy commented on src/qt_gui/checkUpdate.cpp
Filename should be `check_update.cpp`/`check_update.h`

2024-09-21 20:45 UTC, polybiusproxy commented on src/common/scm_rev.cpp.in
> +#define BUILD_DATE "@BUILD_DATE@"
Missing indentation

2024-09-22 07:59 UTC, polybiusproxy commented
You haven't updated the filenames on the Qt files

2024-09-22 14:25 UTC, DanielSvoboda commented
> You haven't updated the filenames on the Qt files

Which file is missing?
I renamed the 2 you mentioned check_update.cpp/check_update.h
![image](https://github.com/user-attachments/assets/b051dcbe-c710-475d-b54b-0ddbfd20eb51)

2024-09-24 20:03 UTC, merged