Videocodec implementation
shadps4-emu/shadPS4 pull request #1484
Opened 2024-11-05 05:06 UTC by georgemoralis

Based on @polybiusproxy  videodec2 implementation . Seems to work , reply with tests thanks :D

2024-11-05 11:40 UTC, bigol83 commented
Resident Evil 4 2005 fmv works without issues

![Immagine 2024-11-05 124118](https://github.com/user-attachments/assets/471a889c-2ae9-4035-ae99-686d5cf0dbab)

2024-11-05 13:45 UTC, ElBread3 commented
think this could be rebased so I can test with ajm?

2024-11-05 14:18 UTC, georgemoralis commented
done

2024-11-05 17:07 UTC, polybiusproxy requested changes
Looks good at first glance, I do have a few nits though.

To start, this one is quite personal, I quite dislike the lack of empty newlines on some functions--to take one example:
```cpp
int PS4_SYSV_ABI sceVideodecFlush(OrbisVideodecCtrl* pCtrlIn,
                                  OrbisVideodecFrameBuffer* pFrameBufferInOut,
                                  OrbisVideodecPictureInfo* pPictureInfoOut) {
    LOG_INFO(Lib_Videodec, "called");

    if (!pFrameBufferInOut || !pPictureInfoOut) {
        return ORBIS_VIDEODEC_ERROR_ARGUMENT_POINTER;
    }
    if (pFrameBufferInOut->thisSize != sizeof(OrbisVideodecFrameBuffer) ||
        pPictureInfoOut->thisSize != sizeof(OrbisVideodecPictureInfo)) {
        return ORBIS_VIDEODEC_ERROR_STRUCT_SIZE;
    }
    VdecDecoder* decoder = (VdecDecoder*)pCtrlIn->handle;
    if (!decoder) {
        return ORBIS_VIDEODEC_ERROR_HANDLE;
    }
    return decoder->Flush(*pFrameBufferInOut, *pPictureInfoOut);
}
```

I believe it would look better this way:
```cpp
int PS4_SYSV_ABI sceVideodecFlush(OrbisVideodecCtrl* pCtrlIn,
                                  OrbisVideodecFrameBuffer* pFrameBufferInOut,
                                  OrbisVideodecPictureInfo* pPictureInfoOut) {
    LOG_INFO(Lib_Videodec, "called");

    if (!pFrameBufferInOut || !pPictureInfoOut) {
        return ORBIS_VIDEODEC_ERROR_ARGUMENT_POINTER;
    }
    if (pFrameBufferInOut->thisSize != sizeof(OrbisVideodecFrameBuffer) ||
        pPictureInfoOut->thisSize != sizeof(OrbisVideodecPictureInfo)) {
        return ORBIS_VIDEODEC_ERROR_STRUCT_SIZE;
    }

    VdecDecoder* decoder = (VdecDecoder*)pCtrlIn->handle;
    if (!decoder) {
        return ORBIS_VIDEODEC_ERROR_HANDLE;
    }

    return decoder->Flush(*pFrameBufferInOut, *pPictureInfoOut);
}
```
clang-format doesn't mind it, but I do.

Secondly, I ask you to change the names of function arguments and struct members to avoid using Hungarian notation which would go against the whole code style from the emulator, so rename things like `pPictureInfoOut` to `pictureInfo`. It wouldn't make sense either way since you're also using it on references.

Finally, since this class is named `VdecDecoder`, to avoid confusion I believe we should either change the Vdec2 implementation class's name to `Vdec2Decoder` or make a common class for both classes to inherit from.

2024-11-05 17:07 UTC, polybiusproxy commented on src/core/libraries/videodec/videodec_impl.cpp
> +        pPictureInfoOut.isErrorPic = false;
You're not outputting codec info, games may try to use info such as frame crop offsets.

2024-11-05 17:07 UTC, polybiusproxy commented on src/core/libraries/videodec/videodec_impl.cpp
> +        pPictureInfoOut.codecType = 1;
Codec type should be zero.

2024-11-05 17:07 UTC, polybiusproxy commented on src/core/libraries/videodec/videodec_impl.cpp
> +        pPictureInfoOut.codecType = 1;
Codec type should be zero.

2024-11-08 15:42 UTC, roamic commented on src/core/libraries/videodec/videodec_impl.cpp
> +    std::memcpy(dst + (src.width * src.height), src.data[1], (src.width * src.height) / 2);
As far as we are aware of, Vdec1 aligns `width` and `height` to `16` so it needs the conversion logic from `avplayer_source.cpp` where the actual data returned by ffmpeg is laid out in the buffer correctly. This is an assumption though, so needs testing and finding an actual game that breaks if it is not implemented.

2024-11-08 15:42 UTC, roamic commented on src/core/libraries/videodec/videodec_impl.cpp
> +        CopyNV12Data((u8*)pFrameBufferInOut.pFrameBuffer, *frame);
While each packet usually contains only one frame, it can contain multiple. Judging from this code you re-write the previously written frame if it is the case. Again, not sure it's relevant, but good to keep in mind while testing. The artifacts it can cause is sped up video output.

2024-11-08 15:42 UTC, roamic commented on src/core/libraries/videodec/videodec_impl.cpp
> +        CopyNV12Data((u8*)pFrameBufferInOut.pFrameBuffer, *frame);
Same issue with possible multiple frames per packet.

2024-11-08 15:42 UTC, roamic commented on src/core/libraries/videodec/videodec_impl.cpp
> +        u32 width = Common::AlignUp((u32)frame->width, 16);
If you align up you should also correct the `CopyNV12Data` function to account for it.

2024-11-10 09:19 UTC, vladmikhalin approved these changes

2024-11-10 09:33 UTC, merged