Add freedesktop metadata
shadps4-emu/shadPS4 pull request #1495
Opened 2024-11-06 20:46 UTC by fpiesche

This adds a new `dist` directory intended for files specific to distributions rather than actually part of the code or executable/bundle, containing the Linux desktop launcher (which currently lives in the `.github` directory for some reason) as well as FreeDesktop `metainfo.xml` and `releases.xml` files. The XML files contain metadata that can be used by Linux desktop environments to display information about the package - this is, for example, used by Flathub for their web listings.

The `releases.xml` file currently needs updating manually. I'm working on a GitHub action that can automatically update these files when a new GitHub release is made; once I've done this and tested it I'll submit a PR with a workflow to keep this file up to date along with GitHub releases :)

2024-11-06 22:17 UTC, fpiesche commented
Should I move the AppImage build scripts into the `dist` folder as well, and the png icon to `src/images` where the other icons are?

2024-11-07 12:26 UTC, jardon commented
> Should I move the AppImage build scripts into the `dist` folder as well, and the png icon to `src/images` where the other icons are?

im going to say confidently, probably

2024-11-07 12:38 UTC, jardon requested changes
I think you should remove the change of the name field in the desktop shortcut and have that change be merged in this [PR](https://github.com/shadps4-emu/shadPS4/pull/1491)

2024-11-07 12:38 UTC, jardon commented on .github/linux-appimage-qt.sh
>  mv Shadps4-x86_64.AppImage Shadps4-qt.AppImage
the appimage name wont match here

2024-11-07 12:38 UTC, jardon commented on .github/linux-appimage-sdl.sh
>  mv Shadps4-x86_64.AppImage Shadps4-sdl.AppImage
the appimage name wont match here

2024-11-08 09:41 UTC, ngoquang2708 commented
Update ```REUSE.toml``` for newly added/moved files or else CI will fail.

2024-11-09 19:51 UTC, jardon approved these changes
LGTM

2024-11-10 03:47 UTC, ngoquang2708 commented on CMakeLists.txt
> +
Empty newline.

2024-11-10 03:47 UTC, ngoquang2708 commented
LGTM.

2024-11-10 06:01 UTC, ngoquang2708 approved these changes

2024-11-13 18:48 UTC, jardon commented
@fpiesche can you resolve the conflicts so we can get this merged?

2024-11-14 08:34 UTC, fpiesche commented
Ended up just exporting my changes to a patch, deleting my local branch, re-creating it and applying the patch to that. Apparently I've temporarily forgotten how to do a rebase without making a mess ._.

2024-11-14 08:56 UTC, merged