misc changes, part ?/?
shadps4-emu/shadPS4 pull request #441
Opened 2024-08-15 12:27 UTC by dima-xd

Saw some games were using these calls

2024-08-15 12:49 UTC, gandalfthewhite19890404 commented
Used at least by:
Ghost Song - CUSA33533
Surviving The Aftermath - CUSA15495

2024-08-15 17:14 UTC, psucien requested changes

2024-08-15 17:14 UTC, psucien commented on src/core/libraries/videoout/video_out.cpp
> +int PS4_SYSV_ABI sceVideoOutGetEventId(const Kernel::SceKernelEvent* ev) {
This should return `INVALID_EVENT` if not a VO event passed

2024-08-15 17:14 UTC, psucien commented on src/core/libraries/videoout/video_out.cpp
> +    *data = ev->data;
Lack of check for address validness and the same as above

2024-08-16 17:12 UTC, raphaelthegreat commented
What about this?

2024-08-16 17:13 UTC, dima-xd commented
> What about this?

This too

2024-08-16 17:16 UTC, merged