video_core: Add bounds checking for subspan use in liverpool functions
shadps4-emu/shadPS4 pull request #717
Opened 2024-09-01 18:48 UTC by baggins183

I have seen Nop packets that exceed the remaining submission length for the command list. When this happens, for me subspan underflows and returns a span with a very high, garbage size, which causes the ProcessCompute function to keep looping.
This commit adds an error message when this happens, and returns an empty span so at least the loop bails out.

Also adds stub cases for type 0 and 1 packets in ProcessCompute

Happens in CUSA01127 (PT)

2024-09-01 18:56 UTC, raphaelthegreat commented on src/video_core/amdgpu/liverpool.cpp
> +static std::span<const u32> checked_subspan(std::span<const u32> span, size_t offset) {
```suggestion
static std::span<const u32> NextPacket(std::span<const u32> span, size_t offset) {
```
Shorter name and I feel more expressive of what function does

2024-09-01 19:28 UTC, baggins183 commented
maybe should have kept the extra switch in a different commit because it look fucked
but I just found out you can add ?w=1 to the url to show a better diff

2024-09-02 19:00 UTC, psucien requested changes

2024-09-02 19:00 UTC, psucien commented on src/video_core/amdgpu/liverpool.cpp
> +        switch (type) {
Please return it back. Packet type 2 is not used on ASC queue (even for alignment cases as GFX has)

2024-09-03 10:58 UTC, merged