add TR for PR 700
shadps4-emu/shadPS4 pull request #756
Opened 2024-09-03 16:28 UTC by DanielSvoboda

add TR for [PR 700](https://github.com/shadps4-emu/shadPS4/pull/700)

tr("Can't apply cheats before the game is started")

2024-09-03 16:44 UTC, mavethee reviewed
Correct polish translation

2024-09-03 16:44 UTC, mavethee commented on src/qt_gui/translations/pl_PL.ts
> +			<translation>Nie można zastosować cheatów przed rozpoczęciem gry.</translation>
```suggestion
			<translation>Nie można zastosować kodów przed uruchomieniem gry.</translation>
```

2024-09-03 16:46 UTC, DanielSvoboda commented
@mavethee is this right? I added your suggestion, but it seems to have disappeared

2024-09-03 16:47 UTC, mavethee requested changes

2024-09-03 16:47 UTC, mavethee commented on src/qt_gui/translations/pl_PL.ts
> +			<translation>Nie można zastosować cheatów przed rozpoczęciem gry.</translation>
```suggestion
			<translation>Nie można zastosować kodów przed uruchomieniem gry.</translation>
```

Keep translation consistent to other translated strings

2024-09-03 16:48 UTC, mavethee commented
> @mavethee is this right? I added your suggestion, but it seems to have disappeared

I've missclicked things, sorry, weird day 😅 
Current suggestion should be okay.

2024-09-03 16:53 UTC, mavethee commented
Also there's still some things missing in general, like Cancel, Apply, Restore Defaults or macOS exclusives, I wonder is it possible to add thoose to not make this PR oneline-ish?
**_Settings menu:_**
![CleanShot 2024-09-03 at 18 50 34@2x](https://github.com/user-attachments/assets/99942e43-78e2-46d2-89c8-82430601a1ed)
**_ShadPS4's macOS menubar_:**
![CleanShot 2024-09-03 at 18 50 55@2x](https://github.com/user-attachments/assets/f381fcdb-c658-4c7c-b61d-d4f113a45d2b)

2024-09-03 16:59 UTC, DanielSvoboda commented
There are actually some parts of the emulator that haven't been translated, but I think I can add them in a new PR

2024-09-03 19:10 UTC, DanielSvoboda commented
to take advantage of the PR :)
add in settings(settings_dialog.cpp)
Save,Apply,Restore Defaults,Close

2024-09-03 19:12 UTC, mavethee commented
@DanielSvoboda Just noticed, I didn't fully fixed my typo in previous PR

Line 91 in pl_PL.ts
Should be `Katalog zainstalowanych gier` not `Katalog zainstalowanych gry`, would be nice if you could correct that as I cannot suggest changes to something you havent touch 😅

2024-09-03 19:15 UTC, DanielSvoboda commented
line 254 ?

2024-09-03 19:20 UTC, mavethee commented
LGTM 😎

2024-09-03 22:56 UTC, DanielSvoboda commented
This is the only one that is pending, that is not being translated. And I couldn't get it to work.
"Directory to install games"
![image](https://github.com/user-attachments/assets/0e29e48b-d698-431a-817d-b0abc80c9845)

2024-09-04 08:30 UTC, mavethee commented
Ehh sometimes strings doesn't make sense in target language 😆 
Probably another my fuckup.

For installed game version should be `Zainstalowana wersja gry:`
I assume source was just `Game installed:`

![CleanShot 2024-09-04 at 10 27 10@2x](https://github.com/user-attachments/assets/3756d56a-ceba-4f2e-ada2-61505f9f80bb)

2024-09-04 09:57 UTC, merged